# Note: Do not edit this file, if you want to override a variable
# do it in your configuration file before you include this file

# Cyclops Tensor Framework ====================================================
CTF_COMMIT     ?= 968f8f9eb6aab1d6b67d2fcc1a70c9fc3b98adfa
CTF_BUILD_PATH ?= $(abspath lib/build/${CONFIG}/ctf/$(CTF_COMMIT))
CTF_LIB        ?= -L${CTF_BUILD_PATH}/lib -lctf
CTF_INCLUDE    ?= -I${CTF_BUILD_PATH}/include

# ECL =========================================================================
ECL_COMMIT     ?= master
ECL_BUILD_PATH ?= $(abspath lib/build/${CONFIG}/ecl/$(ECL_COMMIT))
ECL_INCLUDE    ?= -I${ECL_BUILD_PATH}/include
ECL_LIB        ?= -L${ECL_BUILD_PATH}/lib -lecl -leclffi -leclgc -leclatomic

# Common Lisp Kimia ===========================================================
CLKIMIA_BUILD_PATH ?= $(abspath lib/build/${CONFIG}/clkimia/)
CLKIMIA_LIB ?= -L$(CLKIMIA_BUILD_PATH) -lclkimia

# GMP =========================================================================
GMP_PATH ?= /usr/lib
GMP_LIB ?= -L$(GMP_PATH) -lgmp

# BLAS ========================================================================
BLAS_INCLUDE ?= -I${BLAS_PATH}/include
BLAS_LIB     ?= -L${BLAS_PATH}/lib -lopenblas

# ScaLAPACK ===================================================================
SCALAPACK_LIB ?= -L${SCALAPACK_PATH}/lib -lscalapack


# GENERAL  ===================================================================
KIMIA_TARGET ?= kimia
