name: CI

on: [push]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # because of the set-env calls
    strategy:
      matrix:
        include:
          - name: ubuntu-gcc-9
            os: ubuntu-latest
            compiler: gcc
            version: "9"
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev openmpi-bin
    - name: Install gmp
      run: |
        sudo apt-get install -y libgmp10
    - name: Install libgfortran
      run: |
        sudo apt-get install -y libgfortran-10-dev
    - name: Make dependencies
      run: make deps CONFIG=gcc-debug
    - name: Make kimia
      run: make CONFIG=gcc-debug
