name: CI

on: [push]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: ubuntu-gcc-4.8
            compiler: gcc
            version: "4.8"

          - name: ubuntu-gcc-4.9
            os: ubuntu-latest
            compiler: gcc
            version: "4.9"

          - name: ubuntu-gcc-5
            os: ubuntu-latest
            compiler: gcc
            version: "5"

          - name: ubuntu-gcc-6
            os: ubuntu-latest
            compiler: gcc
            version: "6"

          - name: ubuntu-gcc-7
            os: ubuntu-latest
            compiler: gcc
            version: "7"

          - name: ubuntu-gcc-8
            os: ubuntu-latest
            compiler: gcc
            version: "8"

          - name: ubuntu-gcc-9
            os: ubuntu-latest
            compiler: gcc
            version: "9"

          - name: ubuntu-latest-gcc-10
            os: ubuntu-latest
            compiler: gcc
            version: "10"

          - name: ubuntu-clang-3.5
            os: ubuntu-latest
            compiler: clang
            version: "3.5"

          - name: ubuntu-clang-3.6
            os: ubuntu-latest
            compiler: clang
            version: "3.6"

          - name: ubuntu-clang-3.7
            os: ubuntu-latest
            compiler: clang
            version: "3.7"

          - name: ubuntu-clang-3.8
            os: ubuntu-latest
            compiler: clang
            version: "3.8"

          - name: ubuntu-clang-3.9
            os: ubuntu-latest
            compiler: clang
            version: "3.9"

          - name: ubuntu-clang-4.0
            os: ubuntu-latest
            compiler: clang
            version: "4.0"

          - name: ubuntu-clang-5.0
            os: ubuntu-latest
            compiler: clang
            version: "5.0"

          - name: ubuntu-clang-6.0
            os: ubuntu-latest
            compiler: clang
            version: "6.0"

          - name: ubuntu-clang-7
            os: ubuntu-latest
            compiler: clang
            version: "7"

          - name: ubuntu-clang-8
            os: ubuntu-latest
            compiler: clang
            version: "8"

    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update
    - name: Install gmp
      run: |
        sudo apt-get install -y libgmp10
    - name: Install openmpi
      run: |
        sudo apt-get install -y libopenmpi-dev
    - name: Install libgfortran
      run: |
        sudo apt-get install -y libgfortran-10-dev
    - name: Install git
      run: |
        sudo apt-get install -y git
    - name: Make dependencies
      run: make deps CONFIG=gcc-debug
    - name: Make kimia
      run: make CONFIG=gcc-debug
